[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

treehouse-format.path = "crates/treehouse-format"
traceli.path = "crates/traceli"
