site = "http://localhost:8080"

[user]
title = "liquidex's treehouse"
author = "liquidex"
description = "a place on the Internet I like to call home"

[defs]
"stitchkit/repo" = "https://github.com/liquidev/stitchkit"
"dawd3/repo" = "https://github.com/liquidev/dawd3"

[emoji]
