site = "http://localhost:8080"

[user]
title = "liquidex's treehouse"
author = "liquidex"
description = "a place on the Internet I like to call home"

[defs]

# My own repositories
"stitchkit/repo" = "https://github.com/liquidev/stitchkit"
"dawd3/repo" = "https://github.com/liquidev/dawd3"
"treehouse/repo" = "https://github.com/liquidev/treehouse"
"dispatchers/repo" = "https://github.com/liquidev/dispatchers"

# Blog posts I like to reference
"article/function_coloring" = "https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/"

[emoji]
