site = "http://localhost:8080"

[user]
title = "liquidex's treehouse"
author = "liquidex"
description = "a place on the Internet I like to call home"

[defs]

# Social garbage
"social/github" = "https://github.com/liquidev"
"social/soundcloud" = "https://soundcloud.com/daknus"

# My own repositories
"stitchkit/repo" = "https://github.com/abyteintime/stitchkit"
"dawd3/repo" = "https://github.com/liquidev/dawd3"
"treehouse/repo" = "https://github.com/liquidev/treehouse"
"dispatchers/repo" = "https://github.com/liquidev/dispatchers"
"abit/repo" = "https://github.com/abyteintime/abit"
"rokugo/repo" = "https://github.com/rokugo-lang/rokugo"

# Blog posts I like to reference
"article/function_coloring" = "https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/"

"word/hyperlink" = "https://en.wiktionary.org/wiki/hyperlink"
"word/iff" = "https://en.wiktionary.org/wiki/iff"

# People
"person/areox" = "https://areox.boo"
"person/ezioleq" = "https://ezioleq.com"
"person/firstbober" = "https://firstbober.com"
"person/vixenka" = "https://github.com/Vixenka"

[emoji]

[pics]
