site = "http://localhost:8080"

[user]
title = "liquidex's treehouse"
author = "liquidex"

[defs]
"stitchkit/repo" = "https://github.com/liquidev/stitchkit"
"dawd3/repo" = "https://github.com/liquidev/dawd3"

[emoji]
hueh = "hueh.png"
