# This string is prepended before each link address.
# Replace this with a different root path if you need to host the site in a subdirectory (eg. "/treehouse").
# Note this does not affect the behavior of `serve`, as the treehouse is always served under /.
# Therefore this is most useful for reverse proxies.
# This variable can also be set using the TREEHOUSE_SITE environment variable.
site = ""

[user]
title = "liquidex's treehouse"
author = "liquidex"
description = "a place on the Internet I like to call home"

[defs]

# Social garbage
"social/github" = "https://github.com/liquidev"
"social/soundcloud" = "https://soundcloud.com/daknus"
"social/listenbrainz" = "https://listenbrainz.org/user/liquidev/"

# My own repositories
"stitchkit/repo" = "https://github.com/abyteintime/stitchkit"
"dawd3/repo" = "https://github.com/liquidev/dawd3"
"treehouse/repo" = "https://github.com/liquidev/treehouse"
"dispatchers/repo" = "https://github.com/liquidev/dispatchers"
"abit/repo" = "https://github.com/abyteintime/abit"
"rokugo/repo" = "https://github.com/rokugo-lang/rokugo"
"mica/repo" = "https://github.com/mica-lang/mica"
"planet_overgamma/repo" = "https://github.com/liquidev/planet-overgamma"

# Blog posts I like to reference
"article/function_coloring" = "https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/"

"word/hyperlink" = "https://en.wiktionary.org/wiki/hyperlink"
"word/iff" = "https://en.wiktionary.org/wiki/iff"

# People
"person/areox" = "https://areox.boo"
"person/ezioleq" = "https://ezioleq.com"
"person/firstbober" = "https://firstbober.com"
"person/vixenka" = "https://github.com/Vixenka"

[redirects.page]
"programming/cxx" = "programming/languages/cxx"
"programming/unreal-engine" = "programming/technologies/unreal-engine"

[emoji]

[pics]
